apiVersion: apps/v1
kind: Deployment
metadata:
  name: labfinal
  labels:
    app: labfinal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: labfinal
  template:
    metadata:
      labels:
        app: labfinal
    spec:
      containers:
      - name: labfinal
        image: zerodaste/labfinal:latest
        ports:
        - containerPort:8085
